### ISSUE TITLE
Unable to get IAM security credentials from EC2 Instance Metadata Service.

### ISSUE THREAD

**Issue by upcesar** [Admiral-Piett/goaws#341]
When using the docker version with the following implementation in C#, which is working in a live AWS:

```csharp
public class AwsQueue
{
    public string QueueUrl { get; set; }
    public string AwsAccessKeyId { get; set; }
    public string AwsSecretAccessKey { get; set; }
    public string AwsSessionToken { get; set; }
}

public class AwsBus(AwsQueue awsQueue)
{
    private readonly AmazonSQSClient _sqsClient = new(RegionEndpoint.USEast1);

    public async Task SendMessage<T>(T message, string messageGroupId)
    {
        string json = JsonSerializer.Serialize(message);

        var request = new SendMessageRequest
        {
            QueueUrl = $"{awsQueue.QueueUrl}/{messageGroupId}",
            MessageBody = json,
            MessageGroupId = messageGroupId
        };

        await _sqsClient.SendMessageAsync(request);
    }

    public async Task<T> ReceiveMessage<T>(string messageGroupId)
    {
        var receiveMessage = await _sqsClient.ReceiveMessageAsync(new ReceiveMessageRequest
        {
            QueueUrl = $"{awsQueue.QueueUrl}/{messageGroupId}",
            MaxNumberOfMessages = 1,
            WaitTimeSeconds = 2
        });

        if (receiveMessage.Messages.Count == 0) return default;

        return JsonSerializer.Deserialize<T>(receiveMessage.Messages[0].Body);
    }
}
```

and the usage
```csharp
public class MyMessage {
   // Skip properties for brevity.
}

var messageGroupId = "local-queue.fifo";
var notification = new MyMessage() { /* Skip initialization for brevity */ }; 
var awsBus = new AwsBus(new AwsQueue () {
   QueueUrl = "http://localhost:4100/100010001000"
});

await awsBus.SendMessage(notification, messageGroupId);

var response = await awsBus.ReceiveMessage<MyMessage>(messageGroupId);
```

Either sending and/or receiving a message, throw the error:
```
Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

Also, I tried removing all the properties on `AwsQueue` but `QueueUrl`, since in the issue #115 mentions that "...goaws does not actually use the credentials". If it does, how can I set up a "fake AWS credential"?

**Comment by upcesar** [comment]
I could solve setting the `ServiceURL` in `AmazonSQSConfig` and passing it on the constructor, as:

```csharp
private readonly AmazonSQSClient _sqsClient = CreateSqsClient(awsQueue);

private static AmazonSQSClient CreateSqsClient(AwsQueue awsQueue)
{
    AmazonSQSConfig amazonConfig = new() { ServiceURL = awsQueue.QueueUrl };
    return new(awsQueue.AwsAccessKeyId, awsQueue.AwsSecretAccessKey, amazonConfig);        
}
```
